### ISSUE TITLE
Moving session length thresholds to API side

### ISSUE THREAD

**Issue by minsulander** [minsulander/vatpls#10]
Is it better moving session length control to API side?

To ease changing highlight values thresholds when session timer is integrated in both PLS and IRIS.

_Originally posted by @maxlk96 in https://github.com/maxlk96/vatpls/issues/7#issuecomment-2394628207_

**Comment by Kalln** [comment]
Implemented in 962911b02b14089e99a3d310604e391a69009a02

available at "/api/sessionthreshold"

"info" being the threshold that informs that controlling time is becoming long.
"warning" being the threshold that warns that the session is long.
