### ISSUE TITLE
Add new controller - automatically removes

### ISSUE THREAD

**Issue by niklasthell** [minsulander/vatpls#19]
Start shift, add new controller, fill in all info. 19 registered controllers added into VATPLS. 6 controllers is automatically removed, timer starts 00:00, then automatically deletes the controller. So 6 controllers can´t be added at the moment.

**Comment by minsulander** [comment]
I think we're missing a "controller already exists" check/error message/user feedback.
All the names Niklas tried to add already exist, and if you enter their CID instead, they get added.
